### ISSUE TITLE
Missing values cause an error

### ISSUE THREAD

**Issue by samclifford** [MilesMcBain/shist#1]
```
data("airquality")
shist(airquality$Ozone)
```

Yields error

`Error in quantile.default(x, c(med, med + delta)) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE`

Passing `na.rm=T` to `shist` returns an error of an unused argument.

While this is fixable by filtering out the NAs, first, `ggplot2`'s `geom_hist` doesn't have this issue.

**Comment by MilesMcBain** [comment]
Nice. I think shist should always permit NA's.

**Comment by MilesMcBain** [comment]
Ignores NAs and issues a warning. Unfortunately the warning can't be shown until after the vis is closed.
